image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
    - build
    - unit_test
    - build_image

build:
    stage: build
    script:
        - dotnet nuget add source "${CI_API_V4_URL}/groups/${CI_PROJECT_NAMESPACE_ID}/-/packages/nuget/index.json" --name gitlab --username nikitaberezhko --password ${PACKAGE_REGISTRY_PAT} --store-password-in-clear-text
        - dotnet restore
        - dotnet build --no-restore
        - dotnet build
    artifacts:
        untracked: true
        when: on_success
        access: all
        expire_in: 10 mins
        paths:
            - "artifacts"
    tags:
    - build_image

unit_test:
    stage: unit_test
    script: dotnet test UnitTests --no-build --verbosity normal
    needs:
        - [build]
    dependencies:
        - "build"
    tags:
    - build_image

build_image:
  stage: build_image
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  only:
    - main
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" --tag "$CI_REGISTRY_IMAGE:latest" --build-arg EXECUTABLE=Api.dll .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  needs:
    - [build]
  dependencies:
    - "build"
  tags:
  - build_image
